let joxx = ["What did the snail who was riding on the turtle's back say? Wheeeee!",
"I was going to tell a time traveling joke, but you guys didn't like it.",
"What do you call a lazy kangaroo? A pouch potato.",
"I used to run a dating service for chickens, but I was struggling to make hens meet.",
"Why do we tell actors to break a leg Because every play has a cast.",
"What does a pig put on dry skin? Oinkment.",
"What do you call it when a snowman throws a tantrum? A meltdown.",
"My uncle named his dogs Timex and Rolex. They're his watch dogs.",
"Did you hear about the guy whose left side was cut off? He's all right now.",
"How do you open a banana? With a mon-key.",
"senior woman and adult daughter laughing on porch",
"MOMO PRODUCTIONS",
"ADVERTISEMENT - CONTINUE READING BELOW",
"Which is faster, hot or cold? Hot, because you can catch cold.",
"What did one plate say to the other plate? Dinner's on me.",
"Why do oranges wear sunscreen? So they don't peel.",
"My wife told me to stop acting like a flamingo, so I had to put my foot down.",
"What do you call a pig that does karate? A pork chop.",
"Where does Batman go to the bathroom? The batroom.",
"What do you call a pony with a sore throat? A little horse.",
"What did the left eye say to the right eye? Between you and me, something smells.",
"What did the mama tomato say to the baby tomato? Catch up!",
"Why didn't the melons get married? Because they cantaloupe.",
"What do you call a fake noodle? An impasta.",
"How did the pig get to the hogspital? In a hambulance.",
"I'm so good at sleeping I can do it with my eyes closed!",
"Why does Humpty Dumpty love autumn? Because he had a great fall.",
"What happens when a strawberry gets run over crossing the street? Traffic jam.",
"Why did the cow jump over the moon? The farmer had cold hands.",
"A termite walks into a bar and says, So, is the bar tender here?",
"How does an octopus go into battle? Well-armed.",
"What do you call a pudgy psychic? A four-chin teller.",
"high angle view of cheerful grandparents talking with granddaughters while sitting on sofa at home",
"KLAUS VEDFELT",
"What do you get when you mix a cocker spaniel, a poodle, and a ghost? A cocker-poodle boo.",
"How do celebrities stay cool? They have many fans.",
"What does a pickle say when he wants to play cards? Dill me in!",
"How much money does a pirate pay for corn? A buccaneer.",
"Where do young trees go to learn? Elementree school.",
"Why do bees have sticky hair? Because they use a honeycomb.",
"How did the student feel when he learned about electricity? Totally shocked.",
"What do you call a bee that can't make up its mind? A Maybe.",
"Why was six afraid of seven? Because 7-8-9.",
"If April showers bring May flowers, what do May flowers bring? Pilgrims.",
"I tried to catch fog yesterday. Mist.",
"What do you call a hippie's wife? Mississippi.",
"Two peanuts were walking down the street. One was a-salted.",
"How can you tell it’s a dogwood tree? By the bark.",
"What did the buffalo say when his kid went to college? Bison.",
"What did the mayonnaise say when the refrigerator door was opened? Close the door, I'm dressing.",
"What's the stinkiest planet? Poopiter.",
"two best friends telling secrets lying in the grass",
"WESTEND61",
"What did one wall say to the other? I'll meet you at the corner.",
"Why don't sharks eat clowns? Because they taste funny.",
"A horse walks into a bar. The bartender says, Why the long face?",
"What did the pirate say when he turned 80? Aye matey.",
"What's black and white and goes round and round? A penguin in the washing machine.",
"How do you organize a space party? You planet.",
"Why couldn't the bicycle stand up by itself? It was two tired.",
"Did you hear the rumor about butter? Well, I'm not going to spread it.",
"Why did the student eat his homework? Because his teacher told him it was a piece of cake.",
"What did one hat say to the other? You wait here, I'll go on ahead.",
"What do you call a dinosaur that crashes his car? Tyrannosaurus Wrecks.",
"I couldn't figure out why the baseball kept getting larger. Then it hit me.",
"What do you call a boomerang that won’t come back? A stick.",
"What did the full glass say to the empty glass? You look drunk.",
"How do you stop a bull from charging? Cancel its credit card.",
"Why don’t we see elephants hiding in trees? Because they’re really good at it.",
"happy multiracial senior women having fun together outdoor   elderly generation people hugging each other at park",
"SABRINA BRACHER",
"What’s the difference between a hippo and a zippo? One’s pretty heavy and the other’s a little lighter.",
"Did you hear the one about the roof? Never mind, it's over your head.",
"I used to hate facial hair...but then it grew on me.",
"A cheese factory exploded in France. Da brie was everywhere.",
"What's a ninja's favorite type of shoes? Sneakers.",
"What's the best smelling insect? A deodor-ant.",
"What do you call a bear without any teeth? A gummy bear.",
"Why was the coach yelling at the vending machine? He wanted his quarter back.",
`Yo mama's so fat, when she fell I didn't laugh, but the sidewalk cracked up.`,
`Yo mama's so fat, when she skips a meal, the stock market drops.`,
`Yo mama's so fat, it took me two buses and a train to get to her good side.`,
`Yo mama's so fat, when she goes camping, the bears hide their food.`,
`Yo mama's so fat, if she buys a fur coat, a whole species will become extinct.`,
`Yo mama's so fat, she stepped on a scale and it said: "To be continued."`,
`Yo mama's so fat, I swerved to miss her in my car and ran out of gas.`,
`Yo mama's so fat, when she wears high heels, she strikes oil.`,
`Yo mama's so fat, she was overthrown by a small militia group, and now she's known as the Republic of Yo Mama.`,
`Yo mama's so fat, when she sits around the house, she SITS AROUND the house.`,
`Yo mama's so fat, her car has stretch marks.`,
`Yo mama's so fat, she can't even jump to a conclusion.`,
`Yo mama's so fat, her blood type is Ragu.`,
`Yo mama's so fat, if she was a Star Wars character, her name would be Admiral Snackbar.`,
`Yo mama's so fat, she brought a spoon to the Super Bowl.`,
`Yo mama's so stupid, she stared at a cup of orange juice for 12 hours because it said "concentrate."`,
`Yo mama's so stupid when they said it was chilly outside, she grabbed a bowl.`,
`Yo mama's so stupid, she put lipstick on her forehead to make up her mind.`,
`Yo mama's so stupid, when they said, "Order in the court," she asked for fries and a shake.`,
`Yo mama's so stupid, she thought a quarterback was a refund.`,
`Yo mama's so stupid, she thought a quarterback was a refund.`,
`Yo mama's so stupid, she got hit by a parked car.`,
`Yo mama's so stupid, when I told her that she lost her mind, she went looking for it`,
`Yo mama's so stupid when thieves broke into her house and stole the TV, she chased after them shouting "Wait, you forgot the remote!"`,
`Yo mama's so stupid, she went to the dentist to get a Bluetooth.`,
`Yo mama's so stupid, she took a ruler to bed to see how long she slept.`,
`Yo mama's so stupid, she got locked in the grocery store and starved to death.`,
`Yo mama's so stupid, when I said, "Drinks on the house," she got a ladder.`,
`Yo mama's so stupid, it takes her two hours to watch 60 Minutes.`,
`Yo mama's so stupid, she put airbags on her computer in case it crashed.`,
`Yo mama's so ugly, she threw a boomerang and it refused to come back.`,
`Yo mama's so old, her social security number is one.`,
`Yo mama's so ugly, she made a blind kid cry.`,
`Yo mama's so ugly, her portraits hang themselves.`,
`Yo mama's so old, she walked out of a museum and the alarm went off.`,
`Yo mama's teeth are so yellow when she smiles at traffic, it slows down.`,
`Yo mama's armpits are so hairy, it looks like she's got Buckwheat in a headlock.`,
`Yo mama's so ugly, when she was little, she had to trick-or-treat by phone.`,
`Yo mama's so ugly, her birth certificate is an apology letter.`,
`Yo mama's so ugly, she looked out the window and was arrested for mooning.`,
`Funniest yo mama jokes of all time`,
`Yo mama's so poor, the ducks throw bread at her.`,
`Yo mama's so poor, she chases the garbage truck with a grocery list.`,
`Yo mama's cooking so nasty, she flys got together and fixed the hole in the window screen.`,
`Yo mama's so depressing, blues singers come to visit her when they've got writer's block.`,
`Yo mama's so short, you can see her feet on her driver's license.`,
`Yo mama's so poor, she can't even afford to pay attention.`,
`Yo mama so big, her belt size is "equator."`,
`Yo mama's so classless, she's a Marxist utopia.`,
`Yo mama so short, she went to see Santa and he told her to get back to work.`,
`Yo mama so scary, the government moved Halloween to her birthday.`,
`Yo mama's so nasty, they used to call them jumpolines 'til yo mama bounced on one.`,
`Yo mama's teeth so yellow, I can't believe it's not butter.`,
`Yo mama's so poor, Nigerian princes wire her money.`,
`Yo mama so dumb, she went to the eye doctor to get an iPhone.`,
`Yo mama's so lazy, she stuck her nose out the window and let the wind blow it.`]


document.getElementsByClassName("joke").innerHTML = joxx[Math.floor(Math.random() * joxx.length)]

let btn = document.getElementById("btn");


function jokk() {
  let index = Math.floor(Math.random() * joxx.length)
  document.getElementsByClassName("joke")[0].innerHTML = joxx[index]
}
btn.addEventListener("click", jokk)
